language: node_js
node_js:
  - "node"
branches:
  only:
    - master
script:
  - ng build --prod
install:
  - npm install
before_script:
  - npm i -g firebase-tools
  - cd functions && npm install
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "mybrilliantcode"
