language: node_js
node_js:
  - "node"
branches:
  only:
    - master
script:
  - ng build --prod
  - npm i -g tslint
  - npm i -g typescript
install:
  - npm install
  - cd functions && npm install
  - cd ../
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "mybrilliantcode"
