language: node_js
node_js:
  - "node"
branches:
  only:
    - master
script:
  - ng build --prod
install:
  - npm install
before_install:
  - 'npm i -g firebase-tools'
  - 'npm i -g tslint'
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
