language: node_js
node_js:
  - "node"
branches:
  only:
    - master
script:
  - ng lint
  - ng build --prod
install:
  - npm install -g firebase-tools
  - npm i
after_success:
  - firebase deploy --project mybrilliantcode --token $FIREBASE_TOKEN
